/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo.aula7;

public class App {
    
    public static void main(String[] args) {
        Caneta bic = new Caneta();
        System.out.println(bic.isAberta());

        bic.abrirFechar(true);
        System.out.println(bic.isAberta());

        bic.definirCor("azul");
        System.out.println(bic.getCor());

    }

}
