/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {
    public static void main(String[] args) {

        Caneta bic = new Caneta();
        
        bic.setNivelTinta(20);

        bic.setCor("preto");

        System.out.println(bic.isTampada());

        bic.tamparDestampar();

        System.out.println(bic.isTampada());

        bic.tamparDestampar();

        System.out.println(bic.getCor());

        System.out.println(bic.getTinta());

        System.out.println(bic.escreve(5));

        System.out.println(bic.getTinta());

    }
}
